workflows:
  build-apk:
    name: Build APK - Pedido PDF
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Check Gradle wrapper
        script: |
          if [ ! -f android/gradlew ]; then
            echo "Gradle wrapper not found. Re-creating android directory."
            rm -rf android
            flutter create .
            flutter pub get
          fi

      - name: Build release APK
        script: |
          flutter build apk --release --no-shrink

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - luisgsierrag@gmail.com
