workflows:
  build-apk:
    name: Build APK - Pedido PDF
    max_build_duration: 20
    environment:
      flutter: stable
      vars:
        BUILD_TYPE: release
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Generate launcher icon
        script: |
          flutter pub run flutter_launcher_icons:main

      - name: Build release APK
        script: |
          flutter build apk --$BUILD_TYPE

    artifacts:
      - build/app/outputs/flutter-apk/app-$BUILD_TYPE.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
