workflows:
  build-apk:
    name: Build APK for Comprobante Pedido
    max_build_duration: 15
    environment:
      flutter: stable
      android:
        ndk: 27.0.12077973
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - luisgsierrag@gmail.com
