workflows:
  build-apk:
    name: Build APK - Pedido PDF
    max_build_duration: 20
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get

      - name: Clean project
        script: |
          flutter clean
          flutter pub get

      - name: Fix NDK version
        script: |
          echo 'android { ndkVersion = "27.0.12077973" }' >> android/app/build.gradle

      - name: Build release APK
        script: |
          flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk

    publishing:
      email:
        recipients:
          - luisgsierrag@gmail.com
